### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by TeleTubby666** [lud99/botw-unexplored#5] opened 2021-03-14 02:23 UTC
When launching the app the screen goes black. Returning to the main menu by pressing the home button still works so the switch is not frozen

**Comment by lud99** [comment] 2021-03-15 11:23
Hi, thanks for reporting this issue. Could you tell me what version of Atmosphere you are using?

Other people have reported black screens aswell and it seems to work if you update atmosphere. 
So you can try updating, but I can also try to fix the issue if I know what version your using

**Comment by aerialdigest** [comment] 2021-03-15 15:12
I use SXOS 3.1.0 and am on fw 10.2.0, when I launch I get a black screen that then just returns to hbmenu. Perhaps the app doesn't support SXOS or requires fw 11.0.0?

**Comment by TeleTubby666** [comment] 2021-03-15 20:04
> Hi, thanks for reporting this issue. Could you tell me what version of Atmosphere you are using?
> 
> Other people have reported black screens aswell and it seems to work if you update atmosphere.
> So you can try updating, but I can also try to fix the issue if I know what version your using

I am using AMS 0.17.0 on FW 10.2.0

I hesitate to update to a more recent version because of the hid-mitm removal.

**Comment by lud99** [comment] 2021-03-26 19:04
Hi. I'm unable to reproduce the black screen on FW 10.2.0 with AMS 0.17, everything works fine for me. I don't know what's causing the problem, but it could be because you're trying to run the app while you're playing BotW. It will be fixed in a future update, which will be released soon. I'm going to close this issue.

**Closed as completed by lud99** 2021-03-26 19:04 UTC

**Comment by TeleTubby666** [comment] 2021-04-11 17:32
Works for me with 2.0 now
